artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/b22f6fe5e95141bc9698c8794f7277bb/artifacts
end_time: 1752421647912
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b22f6fe5e95141bc9698c8794f7277bb
run_name: Default
run_uuid: b22f6fe5e95141bc9698c8794f7277bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1752421647906
status: 3
tags: []
user_id: mle-user
